### PR TITLE
Feature/crossbar router, fixes #3 closes #76

### LINKED ISSUE #3: Connect to Coordinator
**Description:**

The labgrid-client connects to the coordinator to read data provided by the exporters. In the same way the backend shall access the coordinator to retrieve information.

**Acceptance criteria:**
- [ ] Connect to the coordinator
- [x] Send command via WAMP protocal

**Additional information:**
https://github.com/labgrid-project/labgrid/blob/master/labgrid/remote/client.py

### LINKED ISSUE #76: Create a crossbar router for frontend-backend-communication
**Description:**
To ease the setup of the frontend and communication to the labgrid coordinator via labby a crossbar router is needed, to prevent registering RPC functions directly on the coordinator. Additionally it allows the frontend to work without needing to handle authentication.

**Acceptance Criteria:**
- [x] The router ist started by the run.py script
- [x] Router exposes RPCs defined in the [API](/Simon-Deuring/labgrid-frontend-mle/blob/main/python-wamp-client/doc/wamp_api.md)
- [x] RPCs get routed to coordinator and results are sent to the frontend

### PR DESCRIPTION
**Pull request by deathcat0011**
## Added:
* Local Crossbar router for frontend
Changed:
* RPCs get calld on local crossbar router
* RPCs call corresbonding RPCs on labgrid coordinator
* RPCs dont't get leaked onto coordinator
## Missing:
* updated usage

### CODE REVIEW

**Review by Simon-Deuring — CHANGES_REQUESTED** [review]
Finally, after too many tries, I was able to run and test your code. It looks good and returns what we expect from it. Well done!

To make this process shorter for users that are new to our project, you should extend the README.md file (of the project or the python-wamp-client subfolder). The following points should be added:
1. How can a connection between the python-wamp-client and the coordinator be established? -> ssh
2. Users need to have Python of a specific version installed.
3. The associated Python interpreter has to be set in Visual Studio Code in order to run the .py files.
4. Crossbar needs to be installed globally.
5. I also needed to install pywin32 on Windows.

With a list of todos new users won't have to solve a multitude of errors but have a clear path to go. Additionally, the parts of the README.md that belonged to the rudimentary JavaScript backend can be removed then. Apart from that the code is fine.

**Comment by deathcat0011** [comment]
Thanks for the comment, and the testing of the code on a different machine. Glad it eventually worked.

I really don't like to hard code the editor to use into the project setup, but yes the python version should be fixed and the developer should even use a virtual python environment to prevent crosscontamination of python modules with different projects.

The specifict python version to use is anything newer than Python 3.7, which is a requirement of autobahn.
I don't believe it is necessary to install Crossbar globally, it should also work with the python module crossbar, at the same version as the autobahn module. @Simon-Deuring have you noticed a particular problem relating to the local crossbar installation. 

Pywin32 is a crossbar installation requirement of the Crossbar module on windows(see [Crossbar installation guide](https://crossbar.io/docs/Installation-on-Windows/)). I will list this as a separate item in the readme, however I will not include this in the requirements.txt for plattform independence.

The requested fix will follow shortly :)

**Comment by Simon-Deuring** [comment]
Thank you very much!

I have installed crossbar globally, so I can't tell you about the local installation. In the requirements.txt the package versions aren't mentioned, so it makes sense to include as much as possible into the documentation to eliminate sie effects.

**Comment by deathcat0011** [comment]
I have now added the requested changes to the Readme and requirements.txt file. This should make it clearer how the tool is used.

**Review by Simon-Deuring — APPROVED** [review]

**Pull request merged**
